package stepDefinitions;

public enum Context {
	ACTIVE_ROLE_ARRAY, INACTIVE_ROLE_ARRAY, ARRAY_DATA, ARRAY_DATA_2, AREA_ISLAND_ARRAY, REGION_ARRAY, CITY_ARRAY, EXPECTED_AREA_ISLAND, EXPECTED_REGION, USER_ID, PASSWORD

}
